name: Deploy Eshop

on:
  push:
    branches:
      - master

jobs:
  deploy-eshop:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: ./.github/actions
