name: Deploy eshop

on:
  workflow_dispatch:
  push:

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: |
          python -m pip install boto boto3 ansible
      - name: Install additional Ansible dependencies
        run: python -m pip install botocore boto3

      - name: install additional dependencies for ansible which runs in venv
        run: |
          source /opt/pipx/venvs/ansible-core/bin/activate
          python -m pip install boto3

      - name: Prepare SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > key
        shell: bash

      - name: Set SSH key permissions
        run: chmod 600 key

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/ec2_deploy.yml
          configuration: |
            [defaults]
            host_key_checking = False
            ansible_python_interpreter = /usr/bin/python3
          inventory: |
            [localhost]
            127.0.0.1 ansible_connection=local
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          options: |
            --extra-vars access_key=${{ secrets.ACCESS_KEY }}
            --extra-vars secret_key=${{ secrets.SECRET_KEY }}
            --extra-vars session_token=${{ secrets.SESSION_TOKEN }}
