name: Deploy eshop

on:
  workflow_dispatch:
  push:

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: insightsengineering/pip-action@v2
        with:
          packages: |
            boto
            boto3
      - run: pip install boto boto3

      - name: install additional dependencies for ansible which runs in venv
        run: |
          source /opt/pipx/venvs/ansible-core/bin/activate
          python -m pip install boto3

      - name: prepare SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > key
        shell: bash

      - name: Set SSH key permissions
        run: chmod 600 key

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: ansible/ec2_deploy.yml
          # Optional, ansible configuration file content (ansible.cfg)
          configuration: |
            [defaults]
            host_key_checking = False
          # Optional, SSH private key
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Optional, literal inventory file contents
          inventory: |
            [launched]
            ansible_ssh_private_key_file=key
          # Optional, encrypted vault password
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --extra-vars access_key=${{ secrets.ACCESS_KEY }}
            --extra-vars secret_key=${{ secrets.SECRET_KEY }}
            --extra-vars session_token=${{ secrets.SESSION_TOKEN }}
            --extra-vars file_ssh=key
