name: Deploy eshop

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: ././ansible/launch_ec2_instance.yml


